[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Automatically download required libraries
lib_deps =
    micro-ROS/micro_ros_arduino @ ^2.0.7-humble
    madhephaestus/ESP32Servo @ ^3.0.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9

; Standard build flags for stability
build_flags = 
    -Os
    -DCORE_DEBUG_LEVEL=0
    
